### PR TITLE
Fully delegate package installation to rstantools

### PR DESCRIPTION
**Pull request by andrjohns**
With the latest release of `rstantools` (2.3.0), we now support exposing stan functions during the installation process (so you no longer have to manually create the c++ sources).

This PR updates your package structure to fully delegate the installation/configuration to `rstantools`, allowing your package to remain compatible with future versions of `rstan`/`StanHeaders`.

I've also added a GHA R-CMD-CHECK workflow from the `r-lib/actions` repository so you can verify that all still works & passes

### CODE REVIEW

**Comment by jtimonen** [comment]
Thanks!

**Comment by jtimonen** [comment]
So the installation process now seems to generate an `src/` directory, `R/RcppExports.R` and `R/stanmodels.R` inside the *source* location. So should I just `.gitignore` those?

**Comment by andrjohns** [comment]
Yep that would be best

**Comment by andrjohns** [comment]
When you're able, would you mind submitting a new release to CRAN with this PR?

**Comment by jtimonen** [comment]
I tried it, but got a bunch of warnings and notes that I don't get locally with `R CMD check --as-cran`. Some of them are easy to fix but some I might need help with.

**Comment by jtimonen** [comment]
I don't know how to fix this:

```
* checking whether package 'lgpr' can be installed ... WARNING
Found the following significant warnings:
  WARNING: The tools required to build C++ code for R were not found.
```

It is now the only warning that I get on winbuilder with r-devel

**Comment by andrjohns** [comment]
That's not a warning that you need to fix. It's referring to the system being used to run the checks, rather than the configuration of your package itself

**Comment by jtimonen** [comment]
But I also get this on my own mac, even though my c++ toolchain should be okay and the installation works, so I don't really understand what is going on.

**Comment by andrjohns** [comment]
The check/warning has no relation to your package or its configuration, just the system itself. If you receive it on your system, but the tools are installed, then it's just a false positive.

**Comment by jtimonen** [comment]
Okay thanks, I have sent a message to CRAN explaining this.

**Comment by andrjohns** [comment]
@jtimonen It looks like this warning might have rstantools-related after all (apologies for the misdirection!), since it's also being seen in another package using the same framework. 

Did CRAN have a response to your message? I'm trying to replicate locally (no luck yet), but was hoping that they might have responded with more context/information

**Comment by jtimonen** [comment]
No they haven't responded

**Comment by andrjohns** [comment]
Sorry again for the wrong advice! The warning occurs when calling `rstan::expose_functions()` with `rstan 2.21` and only when rstudio isn't being used, which was why this was missed initially.

I've submitted a PR to rstantools to fix the warning, and I'll let you know when it's on CRAN

**Comment by andrjohns** [comment]
rstantools 2.3.1 has been released and now the warning should no longer pop up

**Comment by andrjohns** [comment]
@jtimonen sorry to double-ping, but would you mind trying the submission again soon?

**Comment by jtimonen** [comment]
Done

**Comment by andrjohns** [comment]
> Done

Thanks, very much appreciated!

**Comment by jtimonen** [comment]
https://cran.r-project.org/web/packages/lgpr/index.html <- now on CRAN (binaries not yet updated)

**Pull request merged**
